"""lxml build helpers and runtime staging for Nanvix CPython."""

from __future__ import annotations

import shutil
from pathlib import Path

import sys as _sys

_sys.path.insert(0, str(Path(__file__).resolve().parent))
from _loader import load_sibling

config = load_sibling("config", __file__)

_SETUP_LOCAL_TEMPLATE = """\
# Auto-generated by .nanvix/lxml.py -- do not edit manually.

# Statically-linked extension modules for Nanvix builds.
*static*
# Nanvix OS interface module (snapshot, host-mount).
_nanvix _nanvixmodule.c

# Phase 4 of the .a -> .so migration: lxml C extension modules are
# loaded via dlopen at runtime (see Modules/lxml_etree_builtin.c and
# Modules/lxml_elementpath_builtin.c). The shim source files compile
# into thin .so wrappers; the actual lxml/libxslt/libexslt/libxml2
# code lives in liblxml_etree.so + liblxml_elementpath.so staged into
# sysroot/lib/ by .nanvix/test.py and .nanvix/package.py. No per-
# module `-L`/`-l` flags here -- the Nanvix dynamic loader walks the
# DT_NEEDED chain (esaurez/nanvix#27 + #28) at dlopen time.
*shared*
# Phase 0 of the .a -> .so migration: array as proof-of-concept shared module.
# See nanvix-todo/cpython-static-to-shared-migration.md section 4.
# Listed BEFORE Setup.stdlib's static declaration so makesetup's
# "first rule wins" semantics make this shared variant take precedence.
array arraymodule.c
_lxml_etree lxml_etree_builtin.c
_lxml_elementpath lxml_elementpath_builtin.c
"""


def generate_setup_local(repo_root: Path, sysroot: Path) -> None:
    """Generate Modules/Setup.local with the dlopen-style lxml entries.

    The template is intentionally independent of `sysroot` now that the
    lxml linkage is resolved at runtime via dlopen rather than at static
    link time; `sysroot` is retained in the signature for call-site
    compatibility.
    """
    del sysroot  # No longer used; kept for call-site compatibility.
    setup_local = repo_root / "Modules" / "Setup.local"
    setup_local.write_text(_SETUP_LOCAL_TEMPLATE, encoding="utf-8")
    print(f"[lxml] Generated {setup_local}")


def clear_setup_local(repo_root: Path) -> None:
    """Remove the generated Modules/Setup.local."""
    setup_local = repo_root / "Modules" / "Setup.local"
    if setup_local.exists():
        setup_local.unlink()
        print(f"[lxml] Removed {setup_local}")


def stage_lxml_runtime(repo_root: Path, sysroot: Path) -> None:
    """Copy lxml Python files from buildroot into the test/package sysroot.

    Looks for lxml in ``.nanvix/buildroot/python-packages/lxml/``.
    Skips gracefully when the python-packages directory is not available.
    """
    lxml_src = repo_root / ".nanvix" / "buildroot" / "python-packages" / "lxml"
    if not lxml_src.is_dir():
        print(
            f"[lxml] Staged lxml package not found at {lxml_src}; "
            "skipping runtime staging."
        )
        return

    py_lib = sysroot / "lib" / config.PYTHON_LIB_DIR
    if not py_lib.is_dir():
        raise RuntimeError(f"Python runtime library directory is missing: {py_lib}")

    dst = py_lib / "lxml"
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(lxml_src, dst)

    # Ensure the etree.py shim explicitly exports names that are not in
    # lxml.etree.__all__ but are expected by downstream packages (e.g.
    # openpyxl imports xmlfile).  The star-import only picks up names
    # listed in __all__; xmlfile/htmlfile are cdef classes omitted from
    # that list.
    _write_etree_shim(dst / "etree.py")

    print(f"[lxml] Staged {lxml_src} -> {dst}")


# The content of the etree.py shim that bridges the built-in _lxml_etree
# C extension to the expected lxml.etree import path.
_ETREE_SHIM = """\
from _lxml_etree import *
from _lxml_etree import _Element, _ElementTree, _Comment, _ProcessingInstruction, ElementBase, QName, _Attrib
from _lxml_etree import xmlfile, htmlfile
"""


def _write_etree_shim(path: Path) -> None:
    """Write (or overwrite) the lxml/etree.py shim with correct exports."""
    path.write_text(_ETREE_SHIM, encoding="utf-8")
